[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ratp_api"
version = "0.1.0"
description = "Get lyrics of any songs, for free."
authors = ["Romeo Phillips"]

[tool.poetry.dependencies]
python = "^3.7"
certifi = "2023.7.22"
requests = "2.31.0"
wheel = "0.41.2"


[build]
script = "build.py"
